import "dotenv/config";
import type { Twin, ProjectType } from "@aivillage/shared";
import { chooseLlm } from "../agent/llmProvider.js";
import { runTwinBeats, type RunDeps } from "./runTwinBeats.js";

// Runs a simulated stretch with a REAL LLM brain (per .env). The twins' actions
// and narratives are generated by the model, not scripted.
//   pnpm --filter @aivillage/backend exec tsx src/sim/liveDemo.ts

let seq = 0;
const id = (p: string) => `${p}-${++seq}`;

function deps(type: ProjectType): RunDeps {
  return {
    newProjectId: () => id("p"),
    newStructureId: () => id("s"),
    newMemoryId: () => id("m"),
    now: () => new Date().toISOString(),
    chooseProjectType: () => type,
    contextFor: () => ({ nearbyTwinNames: ["Lena", "Daniel"], recentMemories: [] })
  };
}

function twin(name: string, zone: string, traits: string[], goals: string[]): Twin {
  return {
    id: id("t"), ownerUserId: null, name, traits, goals,
    avatarSpriteUrl: null, skills: { building: 0, coding: 0, art: 0, social: 0 },
    reputation: 0, locationZone: zone, energy: 3,
    energyUpdatedAt: new Date().toISOString(), isNpc: true
  };
}

async function main(): Promise<void> {
  const llm = chooseLlm();
  console.log(`\nBrain: ${process.env.LLM_PROVIDER ?? "(auto)"} · model: ${process.env.LLM_MODEL ?? "default"}`);
  console.log("══════════════════════════════════════════════════\n");

  const residents = [
    { t: twin("Mehmet", "plaza", ["chaotic inventor"], ["build a grand fountain in the plaza"]), type: "fountain" as ProjectType },
    { t: twin("Aiko", "maker_space", ["meticulous tinkerer"], ["open a workshop for gadgets"]), type: "workshop" as ProjectType }
  ];

  for (const r of residents) {
    try {
      const res = await runTwinBeats(r.t, null, llm, deps(r.type));
      console.log(`▸ ${r.t.name}  @${res.twin.locationZone}`);
      res.narratives.forEach((n) => console.log(`     · ${n}`));
      res.structuresBuilt.forEach((s) => console.log(`     🏗️  built a ${s.type.toUpperCase()}`));
      console.log("");
    } catch (e) {
      console.log(`     (error for ${r.t.name}: ${(e as Error).message})\n`);
    }
  }
}

main();
